=== padenot/XML_DTD_XSLT_Parser/Projet/src/bin/rap3.dtd
<!ELEMENT auteur (prenom, nom)>
<!ELEMENT prenom (#PCDATA)>
<!ELEMENT chapitre (titre*, (p | section)+)>
<!ELEMENT section (titre?, p+)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT rapport (titre,auteur+,resume,chapitre+)>
<!ELEMENT resume (#PCDATA)>
<!ELEMENT titre (#PCDATA|p|titre)*>

<!ATTLIST chapitre
        titre CDATA #IMPLIED
        a CDATA #IMPLIED
        b CDATA #IMPLIED
        c CDATA #IMPLIED
>
<!ATTLIST section
        titre CDATA #IMPLIED
>

=== padenot/XML_DTD_XSLT_Parser/Projet/src/bin/rap3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE rapport SYSTEM "rap3.dtd">
<rapport>
 <titre>Réaliser un compilateur</titre>
 <auteur>
  <prenom>Silverio</prenom>
  <nom>Nino</nom>
 </auteur>
 <resume>Ceci est un extrait du livre "Réaliser un compilateur: 
	les outils Lex et Yacc" de Nino Silverio</resume>
 <chapitre titre="Introduction: concepts de base" a="a" b="b" c="c">
   <section titre="Fonctions et structure d'un compilateur">
    <p>Tout programme rédigé dans un langage de programmation de haut 
	niveau tel que Pascal ou C ne peut être exécuté par un ordinateur 
	que s'il est traduit en instructions exécutables par l'ordinateur, 
	généralement des instructions en langage machine. L'ordinateur qui 
	doit exécuter le programme ainsi traduit est appelé machine cible.</p>
   </section>

   <section titre="Réalisation d'un compilateur">
    <p>Comme l'écriture d'un compilateur est une tâche fort complexe, 
	le programmateur a tout intérêt à travailler en utilisant un langage 
	de programmation de haut niveau.</p>
   </section>
 </chapitre>
</rapport>
